### ISSUE TITLE
Required Permissions

### ISSUE THREAD

**Issue by CCMurphy-dev** [Monitorr/logarr#109]
## Your environment:

- **Operating system**: Lubuntu
- **Webserver**:       NGIX v. 3.8
- **PHP Version**:      7.2.1 x64 NTS
- **Logarr Branch**:   Develop

## Describe your issue:
Hello,
What permissions are needed for logarr to display the log files?
(Sorry if this has been covered already)
Cheers

**Comment by seanvree** [comment]
@dragobath2 

PHP just needs READ privileges at a minimum to display the log files. However, if you want to be able to "Roll" the log, PHP needs WRITE privileges as well.
