### ISSUE TITLE
Errors in Log During update

### ISSUE THREAD

**Issue by pathsny** [Monitorr/logarr#122]
## Your environment:

- **Operating system**: Freenas V 11.2

- **Webserver**:       NGIX v. 3.8

- **PHP Version**:      7.2.16 x64 NTS

- **Logarr Branch**:   Master

## Describe your issue:
When I try to run an update I see errors in the log. It looks like so
Line 0 : PHP message: PHP Warning: fclose() expects parameter 1 to be resource, boolean given in /usr/local/www/logarr/assets/php/version_check.php on line 7" while reading response header from upstream, client: 192.168.1.81, server: localhost, request: "POST /assets/php/version_check.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "192.168.1.88", referrer: "http://192.168.1.88/" 
Line 1 : PHP message: PHP Warning: fgets() expects parameter 1 to be resource, boolean given in /usr/local/www/logarr/assets/php/version_check.php on line 6 
Line 2 : PHP message: PHP Warning: fopen(https://raw.githubusercontent.com/Monitorr/logarr/master/assets/js/version/version.txt): failed to open stream: No such file or directory in /usr/local/www/logarr/assets/php/version_check.php on line 5

**Comment by seanvree** [comment]
@pathsny  Can you reach that link from the same server Logarr is installed on?


https://raw.githubusercontent.com/Monitorr/logarr/master/assets/js/version/version.txt

This usually means that the server can't reach that link for whatever reason. 

Let me know. 

Thanks

**Comment by pathsny** [comment]
Yes I can. Sorry I should have mentioned that first.

**Comment by seanvree** [comment]
@pathsny  humm. I'm not sure then. I've never seen this before.  Do you by chance have the PHP extension "openssl" installed? If NOT, install that from your php.ini file and see what happens.

**Comment by pathsny** [comment]
I tried this and I don't see errors any longer, but I'm unable to figure out what log to look at to know if it suceeded. What are the log files I shoud look at other than /var/log/nginx/error.log

**Comment by seanvree** [comment]
@pathsny  if the footer says 4.6m then it worked and you're on the latest version. If there's an update it will alert as so. So looks like that fixed it.
