### ISSUE TITLE
Add WIKI

### ISSUE THREAD

**Issue by seanvree** [Monitorr/logarr#16]
**Subjects:**

**USAGE**
1 - Ensure your logs are rolling over !!!!
2 - Ensure your logs are rolling over !!!!
3 - log files size
4 - Auto update
a.  update interval - NO LESS THAN 10 seconds!
b.  size of logs has huge impact.
c. browser UI/DOM LOCKED during update/search - by design.
4 - sensitive data in logs / exposing to WAN

**CONFIG**

- PHP

 - Cloning repo to SUB DIR of webserver

 - Symlink method:

a.  Hardlink ("mklink /d"): - If user keeps all logs in consolidated location and uses a HARD LINK - to target log file ie, C:\logs\sonarr\sonarr.txt -> c:\programdata\sonarr\sonarr.txt then IF the log is "rolled over" by way of deleting the original log file (as opposed to overwriting the data in the same file and re-creating it), the link will break, and Logarr will show the outdated log data that is left over in the dead file link (C:\logs\sonarr.txt). 
Advantage:  Logarr will always show true log file size as long as file link is valid
Disadvantage:  If logs are rolled over frequently, Logarr MAY display outdated log data.

b.  Softlink ("mklink"):  If user uses the soflink method, and the log is "rolled over" using ANY method, as long as the target file name stays the same, Logarr will always display the latest log file data.  HOWEVER - Log file sizes will always show 0KB in the webui. 

c.   user chooses to simply use the original log file path in the Logarr config file, and NOT use file linking at all, none of the above applies.

- Webserver CONFIGs
 a. Protecting via nginx with .htaccess
 b. Protecting via org auth
 c.  Static/dynamic compression?

**FAQ:**
1 - Why is the UI deformed with weird HTML?
a) programs that include HTML in raw text.  See: https://github.com/Monitorr/logarr/issues/8
2 - Why are log files outdated in Logarr but NOT in application logs?
a) Symlink method used (See Config)
3 - Mobile browsing: May or may not work... not designed for mobile due to the large amounts of data that is xfered. 
4) How to add dynamically-named log files:  see https://github.com/Monitorr/logarr/issues/57

**Comment by seanvree** [comment]
@jonfinley  - add any subjects you feel are necessary.

**Comment by jonfinley** [comment]
- Protecting via nginx with .htaccess

- Protecting via org auth

**Comment by seanvree** [comment]
@jonfinley 

Roger, I think we might add in a sub section to the wiki that would address webserver specific situations. But, yes, good call.

**Comment by seanvree** [comment]
Added wiki. Closed.
