### ISSUE TITLE
FEAT: Support Docker Logs

### ISSUE THREAD

**Issue by kmlucy** [Monitorr/logarr#22]
It would be great if Logarr could support logs from Docker containers. I was able to successfully print the logs for a container (named 'logarr' in this instance) by running:

`curl --unix-socket /var/run/docker.sock "http://localhost/v1.24/containers/logarr/logs?stdout=1"`

This is with curl, but Go and Python are both supported as well. If there were an option in the config file to set the container name, the Docker API could be used to pull the logs.

Some information:
https://docs.docker.com/engine/api/get-started/#print-the-logs-of-a-specific-container

**Comment by seanvree** [comment]
@jonfinley  - Don't you use docker?

**Comment by jonfinley** [comment]
@seanvree nope, but this is good to look into.

**Comment by peedub** [comment]
You can get the location of a container log using the following command: `docker inspect --format='{{.LogPath}}' my-container`

I was trying to figure out how to combine this with the other issue - using dynamic logs - but with no success yet.

**Comment by seanvree** [comment]
@peedub  Yeah, I have an idea. I haven't been able to work on this project much lately since I've thrown all my time at Monitorr, but I have a whole bag of stuff I need to implement into the project.

**Comment by seanvree** [comment]
@si0972  do you have any idea how to do this?

**Comment by JigSawFr** [comment]
Great idea ! 👍

**Comment by vertig0ne** [comment]
https://docs.docker.com/engine/api/v1.30/#operation/ContainerLogs

**Comment by seanvree** [comment]
@vertig0ne  NICE! Thanks brotha!
