### ISSUE TITLE
FEAT: Add Catagories

### ISSUE THREAD

**Issue by kmlucy** [Monitorr/logarr#24]
If you are monitoring a lot of files, it would be great to be able to put them on different pages. For example, you could have a webserver page with Apache, PHP, NGINX, etc., a media page with Plex, Radarr, Sonarr, Ombi, etc. That way you don't have one huge page with dozens of log files.

**Comment by seanvree** [comment]
@kmlucy  humm... This is a pretty good idea.  Maybe some type of "tabbed" function.  

THX!

**Comment by rob1998** [comment]
I've added this in, so will be in the settings update
