### ISSUE TITLE
FEAT:  Add Light Theme

### ISSUE THREAD

**Issue by seanvree** [Monitorr/logarr#26]
Add LIGHT theme, Dark to stay default. 

P.S.  I don't want to get into theming here as this project's goal is to stay "minimal" but I think adding a LIGHT them, and Possibly one more would be beneficial.

**Comment by jonfinley** [comment]
for later usage: 
```
$('#grayscale').click(function (){
   $('link[href="style1.css"]').attr('href','style2.css');
});
$('#original').click(function (){
   $('link[href="style2.css"]').attr('href','style1.css');
});
```

**Comment by seanvree** [comment]
Also this code is pretty easy:

https://github.com/denysvitali/thebestmotherfuckingwebsite/issues/13

**Comment by seanvree** [comment]
Meh, won't add. Dumb idea.
