### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by kmlucy** [Monitorr/logarr#36]
I made a basic Docker image available at [kmlucy/docker-logarr](https://github.com/kmlucy/docker-logarr). If you guys want to link to it as another way to run Logarr, you are more than welcome to.

**Comment by seanvree** [comment]
@kmlucy ! Thanks brother!


hey @jonfinley  can we copy this and add it as a branch? Or what's the best way to do this?  I don't use docker.

**Comment by seanvree** [comment]
@kmlucy  thanks for this buddy. 

Created a branch called Docker: https://github.com/Monitorr/logarr/tree/docker

Automated build enabled on Dockerhub here:  https://hub.docker.com/r/monitorr/logarr/
