### ISSUE TITLE
FEAT: timestamp from when logs were grabbed.

### ISSUE THREAD

**Issue by si0972** [Monitorr/logarr#39]
I usualy leave a tab with logarr open, and often find myself questioning when i updated the page.

**Comment by seanvree** [comment]
@si0972  humm....Yeah, I can see that.  Thanks!

**Comment by seanvree** [comment]
Closed - I should prob state that the logs are "grabbed" every time you hit refresh on the browser and not again UNTIL you hit refresh.  It's not a "live" application per-se.

**Comment by si0972** [comment]
I know, i dont think you get me. say, i load the site 4:12, goes afk, and comeback to look at some cat pics, then i switch to the logarr tab at 4:20, wondering if i refreshed when i sat down or before i went AFK.

**Comment by seanvree** [comment]
ahhhh, I see what you're saying.. Yeah, I actually like that!  Reopening.

**Comment by seanvree** [comment]
@si0972 

![image](https://user-images.githubusercontent.com/8906637/35362795-b1820232-011b-11e8-979b-0cbb3b15a8b0.png)

**Comment by seanvree** [comment]
pushed to develop for testing

**Comment by seanvree** [comment]
added with version 3.6
