### ISSUE TITLE
FEAT: increase padding

### ISSUE THREAD

**Issue by si0972** [Monitorr/logarr#53]
i often find myself scrolling trough logs instead of the page, so when i want the log of the bottom i start to scroll the log before the actual page. to not do this i need to move my coursor, this is fine, but i find it requireing too much effort with the smal padding.

**Comment by seanvree** [comment]
got it.

**Comment by seanvree** [comment]
@si0972  Thanks for the suggestion.  Just to be clear, you're talking about the space between the log frame and the actual browser window right?  Highlighted in yellow below:

![logarr](https://user-images.githubusercontent.com/8906637/34481914-987839be-ef69-11e7-8394-06f925af8c5a.PNG)

**Comment by si0972** [comment]
Yes

**Comment by seanvree** [comment]
@si0972  will do, got some other stuff to add, so prob a couple days.

**Comment by seanvree** [comment]
Pushed to TEST branch.

**Comment by seanvree** [comment]
currently in DEVELOP branch

**Comment by seanvree** [comment]
added with version 3.1
