### ISSUE TITLE
BUG:  HMTL data from table is inherited on main PHP page 

### ISSUE THREAD

**Issue by seanvree** [Monitorr/logarr#8]
BUG:

If one of the loggers contains certain HTML in their LOG - the main PHP wrapper will inherit that code making the parent PHP page display incorrectly. (see screenshot below)

Workaround:
Determine where the parent PHP page starts displaying incorrectly, and manually CLEAR the target offending LOG file.  You DO NOT need to delete the log, just open the log file and delete it's contents. 

NOTE:  If this is a common occurrence with a specific logger, MOVE the offending logger's LOG path to the end of LOG path list in your index.php file, example:

```
//Add Logs Here
$logs = array(
    "Radarr" => 'C:\ProgramData\Radarr\logs\radarr.txt',
    "MP4 Converter" => 'C:\sickbeard_mp4_automator\info.log',
    "Headphones" => 'C:\logs\headphones\headphones.log',
    "Sonarr" => 'C:\ProgramData\NzbDrone\logs\sonarr.txt',
    "SABNZBd" => 'C:\sabnzbd\logs\sabnzbd.log',
    "NZBHydra" => 'C:\logs\nzbhydra\nzbhydra.log',
  "Sonarr" => 'C:\ProgramData\NzbDrone\logs\sonarr.txt',
);
```

IN example below, SONARR is making the PHP wrapper page display incorrectly.  

Screenshot:

![logarrdisplayerror](https://user-images.githubusercontent.com/8906637/28757977-7fec5fba-7543-11e7-9875-bf77a5bfb1a8.png)

**Comment by jonfinley** [comment]
I've had an nginx error pop through (sonarr crashed) but it stayed inside the wrapper. just thought I'd add

**Comment by kmlucy** [comment]
I don't know much web development, but could you use something like this? 

http://www.php.net/manual/en/function.htmlspecialchars.php

**Comment by seanvree** [comment]
Def this:

http://matthewjamestaylor.com/blog/convert-special-characters-to-html-entities-between-code-tags

**Comment by seanvree** [comment]
@causefx

Do you have any idea how to fix this?  Weird HTML tags in the raw log files are being interpreted in the DOM making the raw text show up as HTML. 

Pretty rare, but really bothersome.

**Comment by seanvree** [comment]
Fix applied, Currently in DEVELOP branch for testing

**Comment by seanvree** [comment]
added with v3.1
