### ISSUE TITLE
Docker Build - Only Develop or Master

### ISSUE THREAD

**Issue by ShoGinn** [Monitorr/logarr#94]
Just wanted to see if you could add the automated docker builds for your alpha build as well?

**Comment by seanvree** [comment]
@ShoGinn  we don't have plans to add it specifically to the main branch as our alpha is usually on the bleeding edge of development, however, if you want to give it a go, try the below DH image.  However, I would NOT use this on your normal logarr image.  

https://hub.docker.com/r/monitorr/logarr-alpha/

**Comment by seanvree** [comment]
also @ShoGinn  We are getting ready to push a MAJOR update to the dev branch Friday night (Seattle time) so if you can wait, that would be the best.
